name: pyfor_env

channels:
  - conda-forge
dependencies:
  - poppler<0.62
  - python=3.6
  - numpy
  - gdal
  - pandas
  - scipy
  - scikit-image
  - scikit-learn
  - pyqtgraph
  - matplotlib
  - pyopengl
  - plotly
  - numba
  - rasterio>1.0
  - libkml
  - geopandas
  - joblib
  - pip:
      - laspy
      - sphinx_rtd_theme
      - python-coveralls
      - plyfile
