name: pyfor_env

dependencies:
  - python=3.7
  - numpy
  - gdal
  - pandas
  - scipy
  - scikit-image
  - scikit-learn
  - pyqtgraph
  - matplotlib
  - pyopengl
  - numba
  - rasterio
  - libkml
  - geopandas
  - joblib
  - conda-forge::poppler
  - conda-forge::lastools
  - pip:
      - laspy
      - laxpy
      - sphinx_rtd_theme
      - python-coveralls
      - plyfile
