name: pyfor_env

dependencies:
  - python=3.6
  - numpy
  - gdal
  - pandas
  - scipy
  - scikit-image
  - pyqtgraph
  - matplotlib
  - pyopengl
  - plotly
  - numba
  - pip:
      - laspy
      - sphinx_bootstrap_theme
